[package]
name = "post"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry = "0.23.0"
opentelemetry-stdout = "0.4.0"
opentelemetry_sdk = "0.23.0"
sdk ={path = "../sdk"}
serde_json = "1.0.117"
tokio = "1.37.0"
